### ISSUE TITLE
Suggestion: copy degree of rotation

### ISSUE THREAD

**Issue by AntonioCappiello** [ANGIstudio/Copy-Paste-Position-Size#20]
Hello, amazing tool! Saves me ton of time!

I would like to ask/suggest a new feature which I believe many will find it useful.
Can you make the "copy" action to copy also the angle/degree of rotation of the target element?

**Comment by andrejilderda** [comment]
Awesome! This is [simple to achieve](https://developer.sketch.com/reference/api/#layer), but honestly I'm not using Sketch anymore. Do feel free to open a PR!
